Creates `VendorFolder` rule
globocom/gitlab-lint pull request #20
Opened 2021-10-01 06:09 UTC by thepabloaguilar

I've implemented the `VendorFolder` rule which verifies if there's a vendor folder inside a repo!

I tested all the behavior in my private account:
* Empty Repo
* Repo without the vendor folder
* Repo with the vendor folder
* Repo with deleted repo folder

> Also, I'd like to propose a change to the `Ruler` interface to make `Run` return `(bool, error)`.
> I can open an issue to this!

2021-10-01 14:14 UTC, thepabloaguilar commented
@marcelometal could you review this PR, please?

2021-10-04 14:28 UTC, thepabloaguilar commented
@tcarreira maybe you can help with this, please?

2021-10-05 00:46 UTC, tcarreira commented
Hi @thepabloaguilar Thank you for your work.
Nice job 😃  

I commented some minor issues, just for the sake of keeping it tidy.

Regarding the rule itself, I understand this will identify any repository with any folder called `vendor` regarding the language. This may be the correct implementation, but since I'm not fully aware of the reason why (besides what is described on #9), would you mind writing a small paragraph defending your implementation, please?

2021-10-05 00:47 UTC, tcarreira requested changes
Hi @thepabloaguilar Thank you for your work.
Nice job 😃

I commented some minor issues, just for the sake of keeping it tidy.

Regarding the rule itself, I understand this will identify any repository with any folder called vendor regarding the language. This may be the correct implementation, but since I'm not fully aware of the reason why (besides what is described on #9), would you mind writing a small paragraph defending your implementation, please?

2021-10-05 00:54 UTC, thepabloaguilar commented on rules/my_registry.go
> +	MyRegistry.AddRule(NewVendorFolder())
Yeah, I'll do that tonight!

2021-10-05 00:54 UTC, thepabloaguilar commented on rules/vendor_folder.go
> +		Description: "",
Yeah, I'll do that tonight!

2021-10-05 00:58 UTC, thepabloaguilar commented
@tcarreira I think you're right about your concern about to just check if there's a folder called `vendor`. But I can argue that we don't have a variety of languages that use the same pattern to vendoring the project dependencies!
If you want I can add one more check to check if there's a file called `modules.txt` that's created when you execute `go mod vendor`, this way we have a more strong check, WDYT?

Also, I'll rename it to `GoVendorFolder`!

2021-10-05 01:21 UTC, tcarreira commented
Thanks for making it more clear. 

I'm not proficient in many languages, but I know php has some vendor stuff as well.

Making it specific for go will prevent false positives, while allowing for improvement in the future. *Go* for it :) 

Thank you for your input. 👍👍👍

2021-10-05 01:32 UTC, thepabloaguilar commented
Another thing we can verify is if there's a `go.mod` file too, so the checks will be:
- `go.mod` exists
- `vendor/modules.txt` exists

This way we have a stronger way to verify that since that vending pattern only exists if the project uses go modules (AFIK)

The only possible problem is that we'll have more requests to do, but maybe it isn't something to worry now

WDYT @tcarreira?

2021-10-05 03:42 UTC, thepabloaguilar commented
@tcarreira done, I've followed the last idea of searching for `go.mod` and `vendor/modules.txt`, this way we have a more consistent check!

Also, I would like to ask you when you approve this PR, please, add the `hacktoberfest-accepted` tag if possible! Without that tag this PR won't count for Hacktoberfest just for the Globo's Hacktoberfest!

2021-10-05 11:29 UTC, tcarreira approved these changes
lgtm 👍

2021-10-05 11:29 UTC, merged